[package]
org = "ballerina"
name = "integration_tests"
version = "2.11.0"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-native"
path = "../native/build/libs/log-native-2.11.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-test-utils"
scope = "testOnly"
path = "../test-utils/build/libs/log-test-utils-2.11.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "./lib/io-native-1.7.0-20241218-111600-1da6a3f.jar"
